
name: Deploy HandMade To Ubuntu

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - main
    # Inputs the workflow accepts.
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2 
        with:
          dotnet-version: 7.0

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build
        run: dotnet build

      - name: Publish 
        run: dotnet publish -c Release -o out

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
        
